//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.28 at 10:32:49 PM EDT 
//


package aug.manas.mtconnect.mtdata.stubs;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ExecutionValueType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ExecutionValueType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="READY"/>
 *     &lt;enumeration value="INTERRUPTED"/>
 *     &lt;enumeration value="ACTIVE"/>
 *     &lt;enumeration value="STOPPED"/>
 *     &lt;enumeration value="FEED_HOLD"/>
 *     &lt;enumeration value="PROGRAM_COMPLETED"/>
 *     &lt;enumeration value="PROGRAM_STOPPED"/>
 *     &lt;enumeration value="PROGRAM_OPTIONAL_STOP"/>
 *     &lt;enumeration value="UNAVAILABLE"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ExecutionValueType")
@XmlEnum
public enum ExecutionValueType {

    READY,
    INTERRUPTED,
    ACTIVE,
    STOPPED,
    FEED_HOLD,
    PROGRAM_COMPLETED,
    PROGRAM_STOPPED,
    PROGRAM_OPTIONAL_STOP,
    UNAVAILABLE;

    public String value() {
        return name();
    }

    public static ExecutionValueType fromValue(String v) {
        return valueOf(v);
    }

}
