//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.28 at 10:32:49 PM EDT 
//


package aug.manas.mtconnect.mtdata.stubs;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for NotifcationCodeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="NotifcationCodeType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="FAILURE"/>
 *     &lt;enumeration value="FAULT"/>
 *     &lt;enumeration value="CRASH"/>
 *     &lt;enumeration value="JAM"/>
 *     &lt;enumeration value="OVERLOAD"/>
 *     &lt;enumeration value="ESTOP"/>
 *     &lt;enumeration value="MATERIAL"/>
 *     &lt;enumeration value="MESSAGE"/>
 *     &lt;enumeration value="OTHER"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "NotifcationCodeType")
@XmlEnum
public enum NotifcationCodeType {

    FAILURE,
    FAULT,
    CRASH,
    JAM,
    OVERLOAD,
    ESTOP,
    MATERIAL,
    MESSAGE,
    OTHER;

    public String value() {
        return name();
    }

    public static NotifcationCodeType fromValue(String v) {
        return valueOf(v);
    }

}
